Employees.Web/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Employees.Domain.Core;
using Employees.Infrastructure.Data;
using Employees.Domain.Interfaces;

namespace Employees.Web.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeeRepository db;
        public EmployeesController(IEmployeeRepository db)
        {
            this.db = db;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Grid()
        {
            return PartialView(await db.GetEmployees().ToListAsync());
        }


        public ActionResult Create()
        {
            ViewBag.Chiefs = GetChiefsSelectList();

            return PartialView();
        }

        [HttpPost]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Position,ChiefId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                await db.CreateEmployeeAsync(employee);
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            ViewBag.Chiefs = GetChiefsSelectList();

            return PartialView(employee);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.GetEmployeeAsync(id.GetValueOrDefault());
            if (employee == null)
            {
                return HttpNotFound();
            }

            ViewBag.Chiefs = GetChiefsSelectList(id.Value);


            return PartialView(employee);
        }


        [HttpPost]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Position,ChiefId")] Employee employee)
        {
            var chiefs = GetChiefsSelectList();

            if (ModelState.IsValid)
            {
                await db.UpdateEmployeeAsync(employee);
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            return PartialView(employee);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.GetEmployeeAsync(id.GetValueOrDefault());
            if (employee == null)
            {
                return HttpNotFound();
            }
            return PartialView(employee);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await db.DeleteEmployeeAsync(id);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        private SelectList GetChiefsSelectList(int idExcept = 0)
        {
            var employees = db.GetEmployees().AsNoTracking().Where(e => e.Id != idExcept).ToList();
            return new SelectList(employees, "Id", "Name");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Employees.Web/Views/Employees/Create.cshtml
@model Employees.Domain.Core.Employee


<div class="modal-content">
    <div class="modal-header">
        <h2>Create</h2>

    </div>
    <div class="modal-body">
        @using (Html.BeginForm("Create", "Employees", FormMethod.Post, new { id = "createForm" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Employee</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Chief, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ChiefId, ViewBag.Chiefs as SelectList, new { @class = "form-control" })

                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Create" class="btn btn-default" id="createSubmit" />|
                        <a href="" class="cancelButton">Cancel</a>
                    </div>
                </div>
            </div>
        }



    </div>
</div>

Employees.Web/Views/Employees/Delete.cshtml
@model Employees.Domain.Core.Employee

<div class="modal-content">
    <div class="modal-header">

        <h2>Delete</h2>
    </div>
    <div class="modal-body">
        @using (Html.BeginForm("Delete", "Employees", FormMethod.Post, new { id = "deleteForm" }))
            {
            <h3>Are you sure you want to delete this?</h3>
            

                <hr />
                <dl class="dl-horizontal">
                    @Html.HiddenFor(model=>model.Id)
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Position)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Position)
                    </dd>

                </dl>



                <div class="form-actions no-color">
                    <input type="button" value="Delete" class="btn btn-default" id="deleteSubmit" /> |
                    <a href="" class="cancelButton">Cancel</a>
                </div>
                }
            </div>
        </div>
    

Employees.Web/Views/Employees/Details.cshtml
@model Employees.Domain.Core.Employee


<div class="modal-content">
    <div class="modal-header">
        <h4>Employee</h4>
        <hr />
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Position)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Position)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Chief)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Chief.Name)
            </dd>

        </dl>
    </div>
</div>

Employees.Web/Views/Employees/Edit.cshtml
@model Employees.Domain.Core.Employee

<div class="modal-content">
    <div class="modal-header">
        <h2>Edit</h2>

    </div>
    <div class="modal-body">
        @using (Html.BeginForm("Edit", "Employees", FormMethod.Post, new { id = "editForm" }))
        {

            <div class="form-horizontal">
                <h4>Employee</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Chief, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ChiefId, ViewBag.Chiefs as SelectList, new { @class = "form-control" })

                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Save" class="btn btn-default" id="editSubmit" />|
                        <a href="" class="cancelButton">Cancel</a>
                    </div>
                </div>
            </div>
        }


    </div>
</div>

Employees.Web/Views/Employees/Grid.cshtml
@model IEnumerable<Employees.Domain.Core.Employee>

@{
    Layout = null;
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Chief)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chief.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "openModal", @id = "edit-link" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "openModal", @id = "delete-link" })
            </td>
        </tr>
    }

</table>

Employees.Web/Views/Employees/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "openModal", @id = "create-link" })
</p>

<div id="grid">
    Loading...
</div>

@section scripts
{
    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });

            updateGrid();

            $(".container").on("click", ".cancelButton", function (e) {
                e.preventDefault();
                $('#modDialog').modal('hide');
            });

            $(".container").on("click", ".openModal", function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });

            $(".container").on("click", "#editSubmit", function (e) {
                e.preventDefault();
                var form = $('#editForm');
                var data = getFormData(form);
                $.ajax({
                    url: "@Url.Action("Edit", "Employees")",
                    data: JSON.stringify(data),
                    type: "POST",
                    contentType: "application/json;charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        if (data == "") {
                            $('#modDialog').modal('hide');
                            updateGrid();
                        } else {
                            $("#dialogContent").html(data);
                        }
                    }
                });
            });

            $(".container").on("click", "#createSubmit", function (e) {
                e.preventDefault();
                var form = $('#createForm');
                var data = getFormData(form);
                $.ajax({
                    url: "@Url.Action("Create", "Employees")",
                    data: JSON.stringify(data),
                    type: "POST",
                    contentType: "application/json;charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        if (data == "") {
                            $('#modDialog').modal('hide');
                            updateGrid();
                        } else {
                            $("#dialogContent").html(data);
                        }

                    },

                });
            });

            $(".container").on("click", "#deleteSubmit", function (e) {
                e.preventDefault();
                var form = $('#deleteForm');
                var data = { Id: $("[name='Id']", form).val() };
                $.ajax({
                    url: "@Url.Action("Delete", "Employees")",
                    data: JSON.stringify(data),
                    type: "POST",
                    contentType: "application/json;charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $('#modDialog').modal('hide');
                        updateGrid();
                    },

                });
            });

            function updateGrid() {
                $.ajax({
                    url: "@Url.Action("Grid", "Employees")",
                    data: "",
                    type: "POST",
                    contentType: "application/json;charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $("#grid").html(data);
                    }
                });
            };

            function getFormData(form) {
                var data = {
                    Id: $("[name='Id']", form).val(),
                    Name: $("[name='Name']", form).val(),
                    Position: $("[name='Position']", form).val(),
                    ChiefId: $("[name='ChiefId']", form).val()
                };
                return data;
            };

        });
    </script>
}

Employees.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Сотрудники", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Employees")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>